language: objective-c
osx_image: xcode11.3
node_js:
  - "6"

before_script:
  - npm install -g swiftx
  - export SWIFTX_CONFIG_PATH=builds/swift/config

script:
  - swift build
  - swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - swiftx update-build-config
  - swiftx update-dependency-graph
  - swiftx trigger-downstream-builds

after_failure:
  - swiftx trigger-downstream-builds --force
